### ISSUE TITLE
make getLineAtIdx() return a string_view

### ISSUE THREAD

**Issue by Green-Sky** [AidanSun05/ImGuiTextSelect#1]
Hey, is there a reason `getLineAtIdx()` needs to return a `string` (copy) and can't just return a `string_view`? All this copying seems very excessive, since it gets called potentially multiple times per frame. A quick skim of the source did not show any blockers to not just make it a `string_view`.

**Comment by AidanSun05** [comment]
Thanks for the report. When this code was first created as part of NST, there were implementations of `getLineAtIdx` in the project that dynamically computed the returned line, forcing the function to return an `std::string` (not the best decision):

```cpp
std::string Console::getLineAtIdx(size_t i) const {
    // ...

    // Dynamic computation here - this was problematic
    return showTimestamps ? item.timestamp + lineBase : lineBase;
}
```

I've refactored that code to remove the computation and updated ImGuiTextSelect to use `std::string_view`.
