### ISSUE TITLE
Selection not working correctly when containing '\n'

### ISSUE THREAD

**Issue by geertbleyen** [AidanSun05/ImGuiTextSelect#3]
We were looking into a way to have text selection on a ImGui based log window.
All seemed fine at first, until we ran into issues where strings containing lineendings don't work correctly.
In short, ImGui does render the line endings as expected, while the 'overlay' text selection doesn't.
This leads to misaligned selection and overlay.

**Comment by AidanSun05** [comment]
The library assumes each line has the same height. This means strings you pass to it cannot contain newlines, and word wrapping does not work with text selection. If you have something like this:

```cpp
const std::vector<std::string_view> lines{
    "Line 1\nLine 2\n\n",
    "Line 3"
};

std::string_view getLineAtIdx(size_t idx) {
    return lines[idx];
}

size_t getNumLines() {
    return lines.size();
}

// ...

for (const auto& line : lines) ImGui::TextUnformatted(line.data());

textSelect.update();
```

You will need to split the strings by newlines into how they would appear if you rendered them (each string returned by `getLineAtIdx` is a single physical line that appears on screen):

```cpp
const std::vector<std::string_view> lines{
    "Line 1",
    "Line 2",
    "",
    "Line 3"
};
```

This is just a simple example - if your text display is dynamically generated, you will need a splitting function that takes the text to render and outputs lines in a similar format as above.

**Comment by geertbleyen** [comment]
This is exactly what I ended up doing. The contents are dynamic (filterable log window), so it requires adding quite some additional processing (especially if we want to avoid string copies all over the place), but doable.
